complete/blog/api/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *


#app_name='blog'
urlpatterns = [
    path('rest/<int:pk>/', BlogPostRudView.as_view() , name='post-rud'),


    ]

complete/blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

#app_name='blog'
urlpatterns = [
    path('show/<int:pk>/', views.index, name='blog_index'),
    #url(r'^show/(?P<pk>\d+)/$',views.index,name='blog_index'),
    path('post/<int:pk>/', views.details, name='details'),
    path('post/new/<int:pk>/', views.newpost, name='newpost'),
    path('post/<int:pk>/edit', views.editpost, name='editpost'),
    path('post/<int:pk>/delete', views.deletepost, name='deletepost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.addcomment, name='add-comment'),
]

complete/complete/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from accounts.views import home
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from chat.views import index

from put_calendar.api.router import router

from put_calendar.views import *


from rest_framework.authtoken import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('assignments/', include('assignments.urls')),
    url('notifications/', include('notifications.urls')),
    url('clients/', include('clients.urls')),
    url('accounts/',include('accounts.urls')),
    url('history/', include('history.urls')),
    url('^$',home),
    url('blog/', include('blog.urls')),
    url('calendar/',include('put_calendar.urls')),
    url('chat/',include('chat.urls')),
    url('api/posts/',include('blog.api.urls')),
    path('api/',include(router.urls)),
    path('api-token-auth/',views.obtain_auth_token,name='api-token-auth'),


    url(r'^api/dates/$', DatesListView.as_view()),
    url(r'^api/dates/(?P<pk>\d+)/$', DatesView.as_view()),
    url(r'^api/user/$', UserListView.as_view()),
    url(r'^api/user/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^api/filter/(?P<pk>\d+)/$', DatesFilterView.as_view()),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complete/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import teamtable

class post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default='')
    team_details=models.ForeignKey(teamtable, on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.title)

class comment(models.Model):
    post = models.ForeignKey(post, on_delete=models.CASCADE,default='')
    content = models.CharField(max_length=1000)
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.content)

complete/blog/forms.py
from django import forms
from .models import post, comment

class postform(forms.ModelForm):

    class Meta:
        model=post
        fields=('title', 'content',)

class commentform(forms.ModelForm):

    class Meta:
        model=comment
        fields=('content',)

complete/blog/api/views.py
# import django generic views


from  rest_framework import generics
from blog.models import post

from .serializers import postserializer


class BlogPostRudView(generics.RetrieveUpdateDestroyAPIView): #DetailVoew

    pass

    lookup_field =   'pk'   #id   <int:pk>

    serializer_class = postserializer
    #queryset    = BlogPost.objects.all()

    def  get_queryset(self):
        return  post.objects.all()

    # def get_object(self):
    #     pk = self.kwargs.get("pk")
    #     return  post.objects.get(pk=pk)

complete/blog/views.py
from django.http import Http404,HttpResponse
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from blog.models import post, comment
from .forms import postform, commentform
from django.shortcuts import redirect
from accounts.models import teamtable


# Create your views here.

def index(request,pk):
    if pk:
        team=teamtable.objects.get(pk=pk)
        pindex = post.objects.filter(team_details=team).order_by('-timestamp')
        posts_dict_index = {'posts': pindex,'team': team}

        return render(request, 'blog/index.html', posts_dict_index)
    else:
        return HttpResponse("excellent")

def details(request, pk):
    posts = get_object_or_404(post,id=pk)
    comments = comment.objects.filter(post=posts)
    posts_dict_details = {'posts':posts, 'allcomments': comments}
    return render(request, 'blog/details.html', posts_dict_details)


def newpost(request,pk=3):

    if request.method == "POST":
        newform = postform(request.POST)
        if newform.is_valid():
            new_post = newform.save(commit=False)
            title=request.POST['title']
            content=request.POST['content']
            new_post.author = request.user
            new_post.published_date = timezone.now()
            teaming=teamtable.objects.get(pk=pk)
            print(teaming)
            newpost.team_details=teaming
            new_post.save()
            post.objects.create(title=title,content=content,author=request.user,team_details=teaming)
            return redirect('/blog/show/'+str(pk)+'/')
    else:
        newform = postform()
        return render(request, 'blog/newpost.html', {'form': newform})


def editpost(request, pk):
    posts = get_object_or_404(post, pk=pk)
    if posts.author != request.user:
        raise Http404()

    if request.method == "POST":
        editform = postform(request.POST, instance=posts)
        if editform.is_valid():
            edit_post = editform.save(commit=False)
            edit_post.published_date = timezone.now()
            team=edit_post.team_details
            edit_post.save()
            teamid=team.pk

            return redirect('/blog/show/'+str(teamid)+'/')

    else:
        editform = postform(instance=posts)
        return render(request, 'blog/editpost.html', {'form': editform})


def deletepost(request, pk):
    posts = get_object_or_404(post, pk=pk)
    if posts.author != request.user:
        raise Http404()
    team=posts.team_details
    teamid=team.pk
    posts.delete()
    return redirect('/blog/show/'+str(teamid)+'/')

def addcomment(request, pk):
    posts = get_object_or_404(post,pk=pk)
    if request.method == 'POST':
        com_form=commentform(request.POST)
        if com_form.is_valid():
            comment_var =com_form.save(commit=False)
            comment_var.post=posts
            comment.author=request.user
            comment_var.save()
            postid=posts.pk
            return redirect('/blog/post/'+str(postid)+'/')
    else:
        com_form = commentform()
    return render(request, 'blog/addcomment.html',{'form':com_form})

complete/templates/blog/addcomment.html
{% extends 'blog/base.html' %}x

{% block body %}
    <script type="text/javascript">
    $(function(){

        $("#id_content").addClass("form-control");
});
  </script>
    <br><br><br>
    <div class="card" style="width: 60%;height:auto;margin-left: 17%;">
    <div class="card-body">
        <p class="display-4">Add comment</p>
        <hr>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Send</button>
    </form>
    </div>
    </div>
{% endblock %}

complete/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    {% block head %}
    {% endblock head %}
    <title>Disqus</title>



</head>
<body style="background-image:url('{% static 'images/13390.jpg' %}');background-size:cover; background-repeat:no-repeat;">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="navbar-header">
      <a class="navbar-brand" href="/">Kickstart</a>
    </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li><a class="nav-link" href="/accounts/">Home <span class="fa fa-home"></span></a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
            <li><a class="nav-link" href='/accounts/profile'>Profile <span class="fa fa-user"></span></a></li>

              <li><a class="nav-link" href='/accounts/logout'>Logout <span class="fa fa-sign-out-alt"></span></a></li>
            </ul>
            {% else %}
            <ul class="navbar-nav mr-auto">
                <li><a class="nav-link" href="/accounts/index">Home <span class="fa fa-home"></span></a></li>
            </ul>
                        <ul class="navbar-nav ml-auto">
                <li><a class="nav-link" href='/accounts/login'>Login <span class="fa fa-sign-in-alt"></span></a></li>
              <li><a class="nav-link" href="/accounts/inter_reg">Register <span class="fa fa-user-plus"></span></a></li>
            </ul>
            {% endif %}
        </div>

      </nav>

{% block body %}
{% endblock body %}

</body>
</html>

complete/templates/blog/details.html
{% extends 'blog/base.html' %}
{% load  staticfiles %}

{% block head %}
    <style>
        a, a:hover {
            color: #d43e3e;
            text-decoration: none;
        }
    </style>
{% endblock head %}

{% block body %}

    <br><br><br>


    <div class="shadow-lg p-4 mb-4" style="padding: 30px;background-color: #ebebeb;color:#373737;width:85%;margin-left: 7%;">
        <div class="media">
            <img src="{% static 'images/default.png' %}" class="align-self-start mr-3 rounded-circle"
                 style="width:60px">
            <div class="media-body">
                <div class="row">
                    <div class="col-lg-9">
                        <span class="font-italic"><small> posted by</small></span> {{ posts.author }} <br><span class="font-italic"><small>
                    {{ posts.timestamp|date:"g:i A, d M, y" }}</small></span>

                    </div>
                    <div class="col-lg-3">
                        <div class="text-right">
                            {% if request.user == posts.author %}
                        <a class="btn btn-default" href="{% url 'editpost' pk=posts.pk %}"><span
                                class="fa fa-pencil"></span></a>
                        <a class="btn btn-default" href="{% url 'deletepost' pk=posts.pk %}"><span
                                class="fa fa-trash"></span></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <br>
                <hr style="border-color: #63636394;margin: 0px;width: inherit;">
                <h1 class="display-4" style="font-size: 37px">{{ posts.title }}</h1>
                <p style="font-size: large;">{{ posts.content }}</p>
            </div>
        </div>
    <hr style="border-color: #63636394;">
    <br>
        <p class="text-left" style="margin-left: inherit;">
            <a href="{% url 'add-comment' pk=posts.pk %}" class="btn btn-warning btn-sm" role="button"
               style="border-color: #d43e3e;background-color: #d43e3e;color:white;">Add
                comment <span class="fa fa-plus-circle"></span></a>
        </p>

        {% for comment in allcomments %}

            <div class="shadow p-4 mb-4" style="background-color: white;color:black;width: 90%;margin-left:inherit;">
                <div class="media">
                    <img src="{% static 'images/default.png' %}" class="align-self-start mr-3 rounded-circle"
                         style="width:60px">
                    <div class="media-body">
                        <div class="row">
                            <div class="col-lg-10">
                                <h5>{{ comment.author }}:</h5>
                                <p class="font-weight-normal">{{ comment.content }}</p>
                            </div>
                            <div class="col-lg-2">
                        <span class="font-italic"><small>
                    {{ posts.timestamp|date:"d M, y  g:i A" }}</small></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

complete/templates/blog/editpost.html
{% extends 'blog/base.html' %}
{% block body %}
    <script type="text/javascript">
    $(function(){

        $("#id_content").addClass("form-control");
        $("#id_title").addClass("form-control");
});
  </script>
    <br><br><br>

     <div class="card" style="width: 60%;margin-left: 17%;height: auto;">
     <div class="card-body">
        <p class="display-4">Modify post</p>
         <hr>
         <form method="POST">
            {% csrf_token %}

        Title:
        {{ form.title }}<br><br>
            Description:
        {{ form.content }}

        <br><br>
        <button type="submit" class="btn btn-danger">Save</button>
    </form>
     </div>
     </div>
{% endblock %}

complete/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block head %}
    <style>
        a, a:hover {
            color: #3e3e3e;
            text-decoration: none;
        }
    </style>

{% endblock head %}

{% block body %}
    <br><br><br>


    <p class="text-center">
        <a href="{% url 'newpost' pk=team.pk %}" class="btn btn-warning" role="button"
           style="border-radius: 20px;color: white;background-color: #d43e3e;border-color: #d43e3e;">Add
            new post <span class="fa fa-plus-circle"></span></a>
    </p>
    {% if posts %}
        {% for post in posts %}
            <div class="shadow-lg p-4 mb-4" style="background-color: #f7f7f7;color: #373737;width:70%;margin-left: 15%;">
                <div class="media">
                    <img src="{% static 'images/default.png' %}" class="align-self-start mr-3 rounded-circle"
                         style="width:60px">
                    <div class="media-body">
                        <p><span class="font-italic"><small> posted by</small></span><span
                                > {{ post.author }} </span><br><span class="font-italic"><small>{{ post.timestamp|date:"g:i A, d M, y" }}</small></span>
                        </p>
                        <hr style="border-color: #5d5c5c94;margin: 0px">
                        <h1 class="display-4" style="font-size: 37px;"><a href="{% url 'details' pk=post.pk %}">{{ post.title }}</a></h1>
                        <p style="font-size:large;">{{ post.content }}</p>
                        <a href="{% url 'details' pk=post.pk %}">Comments <span class="badge badge-pill badge-primary"
                                                                                style="background-color: #d43e3e">{{ post.comment_set.count }}</span></a>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
    {% endif %}
{% endblock %}

complete/templates/blog/newpost.html
{% extends 'blog/base.html' %}
<style>
    input
</style>
{% block body %}
    <script type="text/javascript">
    $(function(){

        $("#id_title").addClass("form-control");
        $("#id_content").addClass("form-control");
});
  </script>
    <br><br><br>

    <div class="card" style="width: 60%;margin-left: 17%;height:auto;">
    <div class="card-body">
        <p class="display-4">Add post</p>
        <hr>
    <form method="POST">
        {% csrf_token %}
        Title:{{ form.title }}

        Description:
        {{ form.content }}

        <br><br>
        <button type="submit" class="btn btn-danger">Post</button>
    </form>
    </div>
            </div>
{% endblock %}